# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4bc41ccb8dab29806a25858b02771bd6db7ffe67cf1f40071a0be3b4ce2f47eede04a47ecc62755a05bdf486d7cd36ab705bb6ec8c6dc3a537a6f7177a16b84

test:
  secret_key_base: 2dab729fa4ed22c8f8fcfe77d8c1acdf6ef4974832d1f86b947de8291cd67c5e20bd12e42e9b5b2540e3f7cd12e5a3e3838505012f77c77985e9563cf2db2fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
